/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import jogo.Estado;
import jogo.Jogo;

/**
 *
 * @author Laura
 */
public class InterfaceMapa2 extends javax.swing.JFrame {

    ArrayList<Estado> estados = jogo.Jogo.getEstadosSorteados();
    Estado estadoAtual = estados.get(0);
    int posAtual = 0;
    boolean primeiraVez = true;
    boolean acertou = false;
    int pontuacao = 0;

    /**
     * Creates new form InterfaceMapa
     */
    public InterfaceMapa2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoMapaGoias4 = new javax.swing.JButton();
        campoPontuacaoFase2 = new javax.swing.JTextField();
        labelInformativa = new javax.swing.JLabel();
        labelPontuacao = new javax.swing.JLabel();
        labelMostraEstado = new javax.swing.JLabel();
        botaoMapaMatoGrosso = new javax.swing.JButton();
        botaoMapaPara = new javax.swing.JButton();
        botaoMapaMatoGrossoDoSul = new javax.swing.JButton();
        botaoMapaGoias = new javax.swing.JButton();
        botaoMapaAmazonas = new javax.swing.JButton();
        botaoMapaCeara = new javax.swing.JButton();
        botaoMapaPiaui = new javax.swing.JButton();
        botaoMapaRioGrandeDoSul = new javax.swing.JButton();
        botaoMapaSantaCatarina = new javax.swing.JButton();
        botaoMapaParana = new javax.swing.JButton();
        botaoMapaSaoPaulo = new javax.swing.JButton();
        botaoMapaRioDeJaneiro = new javax.swing.JButton();
        botaoMapaEspíritoSanto = new javax.swing.JButton();
        botaoMapaMinasGerais = new javax.swing.JButton();
        botaoMapaBahia = new javax.swing.JButton();
        botaoMapaSergipe = new javax.swing.JButton();
        botaoMapaAlagoas = new javax.swing.JButton();
        botaoMapaPernambuco = new javax.swing.JButton();
        botaoMapaParaiba = new javax.swing.JButton();
        botaoMapaRioGrandeDoNorte = new javax.swing.JButton();
        botaoMapaDistritoFederal = new javax.swing.JButton();
        botaoMapaTocantins = new javax.swing.JButton();
        botaoMapaAmapa = new javax.swing.JButton();
        botaoMapaRoraima = new javax.swing.JButton();
        botaoMapaRondonia = new javax.swing.JButton();
        botaoMapaAcre = new javax.swing.JButton();
        botaoMapaMaranhao = new javax.swing.JButton();
        mapaFase2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(704, 642));
        getContentPane().setLayout(null);

        campoPontuacaoFase2.setText(Integer.toString(pontuacao));
        getContentPane().add(campoPontuacaoFase2);
        campoPontuacaoFase2.setBounds(480, 420, 70, 40);

        labelInformativa.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        labelInformativa.setText("Acerte o estado!");
        getContentPane().add(labelInformativa);
        labelInformativa.setBounds(230, 0, 190, 60);

        labelPontuacao.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        labelPontuacao.setText("Pontos:");
        getContentPane().add(labelPontuacao);
        labelPontuacao.setBounds(430, 430, 60, 20);

        labelMostraEstado.setText(estadoAtual.getNome());
        getContentPane().add(labelMostraEstado);
        labelMostraEstado.setBounds(210, 60, 220, 50);

        botaoMapaMatoGrosso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaMatoGrossoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaMatoGrosso);
        botaoMapaMatoGrosso.setBounds(290, 270, 20, 20);

        botaoMapaPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaParaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaPara);
        botaoMapaPara.setBounds(310, 190, 20, 20);

        botaoMapaMatoGrossoDoSul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaMatoGrossoDoSulActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaMatoGrossoDoSul);
        botaoMapaMatoGrossoDoSul.setBounds(300, 330, 20, 20);

        botaoMapaGoias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaGoiasActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaGoias);
        botaoMapaGoias.setBounds(340, 310, 10, 10);

        botaoMapaAmazonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaAmazonasActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaAmazonas);
        botaoMapaAmazonas.setBounds(210, 190, 20, 20);

        botaoMapaCeara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaCearaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaCeara);
        botaoMapaCeara.setBounds(440, 200, 10, 10);

        botaoMapaPiaui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaPiauiActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaPiaui);
        botaoMapaPiaui.setBounds(410, 230, 10, 10);

        botaoMapaRioGrandeDoSul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaRioGrandeDoSulActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaRioGrandeDoSul);
        botaoMapaRioGrandeDoSul.setBounds(310, 430, 10, 10);

        botaoMapaSantaCatarina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaSantaCatarinaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaSantaCatarina);
        botaoMapaSantaCatarina.setBounds(350, 410, 10, 10);

        botaoMapaParana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaParanaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaParana);
        botaoMapaParana.setBounds(330, 380, 10, 10);

        botaoMapaSaoPaulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaSaoPauloActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaSaoPaulo);
        botaoMapaSaoPaulo.setBounds(360, 360, 10, 10);

        botaoMapaRioDeJaneiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaRioDeJaneiroActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaRioDeJaneiro);
        botaoMapaRioDeJaneiro.setBounds(410, 360, 10, 10);

        botaoMapaEspíritoSanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaEspíritoSantoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaEspíritoSanto);
        botaoMapaEspíritoSanto.setBounds(430, 340, 10, 10);

        botaoMapaMinasGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaMinasGeraisActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaMinasGerais);
        botaoMapaMinasGerais.setBounds(400, 320, 10, 10);

        botaoMapaBahia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaBahiaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaBahia);
        botaoMapaBahia.setBounds(420, 270, 10, 10);

        botaoMapaSergipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaSergipeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaSergipe);
        botaoMapaSergipe.setBounds(460, 260, 10, 10);

        botaoMapaAlagoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaAlagoasActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaAlagoas);
        botaoMapaAlagoas.setBounds(470, 250, 10, 10);

        botaoMapaPernambuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaPernambucoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaPernambuco);
        botaoMapaPernambuco.setBounds(450, 230, 10, 10);

        botaoMapaParaiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaParaibaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaParaiba);
        botaoMapaParaiba.setBounds(470, 220, 10, 10);

        botaoMapaRioGrandeDoNorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaRioGrandeDoNorteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaRioGrandeDoNorte);
        botaoMapaRioGrandeDoNorte.setBounds(460, 210, 10, 10);

        botaoMapaDistritoFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaDistritoFederalActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaDistritoFederal);
        botaoMapaDistritoFederal.setBounds(370, 300, 10, 10);

        botaoMapaTocantins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaTocantinsActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaTocantins);
        botaoMapaTocantins.setBounds(360, 250, 10, 10);

        botaoMapaAmapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaAmapaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaAmapa);
        botaoMapaAmapa.setBounds(330, 140, 10, 10);

        botaoMapaRoraima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaRoraimaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaRoraima);
        botaoMapaRoraima.setBounds(240, 140, 10, 10);

        botaoMapaRondonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaRondoniaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaRondonia);
        botaoMapaRondonia.setBounds(230, 260, 10, 10);

        botaoMapaAcre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaAcreActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaAcre);
        botaoMapaAcre.setBounds(170, 250, 10, 10);

        botaoMapaMaranhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaMaranhaoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaMaranhao);
        botaoMapaMaranhao.setBounds(390, 200, 10, 10);

        mapaFase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Mapa Fase 2.jpg"))); // NOI18N
        getContentPane().add(mapaFase2);
        mapaFase2.setBounds(130, 100, 460, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMapaSantaCatarinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaSantaCatarinaActionPerformed
        // TODO add your handling code here:
        checaResposta("santa catarina");
    }//GEN-LAST:event_botaoMapaSantaCatarinaActionPerformed

    private void botaoMapaRioGrandeDoSulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaRioGrandeDoSulActionPerformed
        // TODO add your handling code here:
        checaResposta("rio grande do sul");
    }//GEN-LAST:event_botaoMapaRioGrandeDoSulActionPerformed

    private void botaoMapaMatoGrossoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaMatoGrossoActionPerformed
        // TODO add your handling code here:
        checaResposta("mato grosso");
    }//GEN-LAST:event_botaoMapaMatoGrossoActionPerformed

    private void botaoMapaAmazonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaAmazonasActionPerformed
        // TODO add your handling code here:
        checaResposta("amazonas");
    }//GEN-LAST:event_botaoMapaAmazonasActionPerformed

    private void botaoMapaAcreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaAcreActionPerformed
        // TODO add your handling code here:
        checaResposta("acre");
    }//GEN-LAST:event_botaoMapaAcreActionPerformed

    private void botaoMapaRondoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaRondoniaActionPerformed
        // TODO add your handling code here:
        checaResposta("rondonia");
    }//GEN-LAST:event_botaoMapaRondoniaActionPerformed

    private void botaoMapaRoraimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaRoraimaActionPerformed
        // TODO add your handling code here:
        checaResposta("roraima");
    }//GEN-LAST:event_botaoMapaRoraimaActionPerformed

    private void botaoMapaAmapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaAmapaActionPerformed
        // TODO add your handling code here:
        checaResposta("amapa");
    }//GEN-LAST:event_botaoMapaAmapaActionPerformed

    private void botaoMapaParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaParaActionPerformed
        // TODO add your handling code here:
        checaResposta("para");
    }//GEN-LAST:event_botaoMapaParaActionPerformed

    private void botaoMapaTocantinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaTocantinsActionPerformed
        // TODO add your handling code here:
        checaResposta("tocantins");
    }//GEN-LAST:event_botaoMapaTocantinsActionPerformed

    private void botaoMapaPiauiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaPiauiActionPerformed
        // TODO add your handling code here:
        checaResposta("piaui");
    }//GEN-LAST:event_botaoMapaPiauiActionPerformed

    private void botaoMapaMaranhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaMaranhaoActionPerformed
        // TODO add your handling code here:
        checaResposta("maranhao");
    }//GEN-LAST:event_botaoMapaMaranhaoActionPerformed

    private void botaoMapaCearaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaCearaActionPerformed
        // TODO add your handling code here:
        checaResposta("ceara");
    }//GEN-LAST:event_botaoMapaCearaActionPerformed

    private void botaoMapaRioGrandeDoNorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaRioGrandeDoNorteActionPerformed
        // TODO add your handling code here:
        checaResposta("rio grande do norte");
    }//GEN-LAST:event_botaoMapaRioGrandeDoNorteActionPerformed

    private void botaoMapaParaibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaParaibaActionPerformed
        // TODO add your handling code here:
        checaResposta("paraiba");
    }//GEN-LAST:event_botaoMapaParaibaActionPerformed

    private void botaoMapaPernambucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaPernambucoActionPerformed
        // TODO add your handling code here:
        checaResposta("pernambuco");
    }//GEN-LAST:event_botaoMapaPernambucoActionPerformed

    private void botaoMapaAlagoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaAlagoasActionPerformed
        // TODO add your handling code here:
        checaResposta("alagoas");
    }//GEN-LAST:event_botaoMapaAlagoasActionPerformed

    private void botaoMapaSergipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaSergipeActionPerformed
        // TODO add your handling code here:
        checaResposta("sergipe");
    }//GEN-LAST:event_botaoMapaSergipeActionPerformed

    private void botaoMapaBahiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaBahiaActionPerformed
        // TODO add your handling code here:
        checaResposta("bahia");
    }//GEN-LAST:event_botaoMapaBahiaActionPerformed

    private void botaoMapaMinasGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaMinasGeraisActionPerformed
        // TODO add your handling code here:
        checaResposta("minas gerais");
    }//GEN-LAST:event_botaoMapaMinasGeraisActionPerformed

    private void botaoMapaGoiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaGoiasActionPerformed
        // TODO add your handling code here:
        checaResposta("goias");
    }//GEN-LAST:event_botaoMapaGoiasActionPerformed

    private void botaoMapaMatoGrossoDoSulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaMatoGrossoDoSulActionPerformed
        // TODO add your handling code here:
        checaResposta("mato grosso do sul");
    }//GEN-LAST:event_botaoMapaMatoGrossoDoSulActionPerformed

    private void botaoMapaDistritoFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaDistritoFederalActionPerformed
        // TODO add your handling code here:
        checaResposta("distrito federal");
    }//GEN-LAST:event_botaoMapaDistritoFederalActionPerformed

    private void botaoMapaEspíritoSantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaEspíritoSantoActionPerformed
        // TODO add your handling code here:
        checaResposta("espirito santo");
    }//GEN-LAST:event_botaoMapaEspíritoSantoActionPerformed

    private void botaoMapaRioDeJaneiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaRioDeJaneiroActionPerformed
        // TODO add your handling code here:
        checaResposta("rio de janeiro");
    }//GEN-LAST:event_botaoMapaRioDeJaneiroActionPerformed

    private void botaoMapaParanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaParanaActionPerformed
        // TODO add your handling code here:
        checaResposta("parana");
    }//GEN-LAST:event_botaoMapaParanaActionPerformed

    private void botaoMapaSaoPauloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaSaoPauloActionPerformed
        // TODO add your handling code here:
        checaResposta("sao paulo");
    }//GEN-LAST:event_botaoMapaSaoPauloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMapa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMapaAcre;
    private javax.swing.JButton botaoMapaAlagoas;
    private javax.swing.JButton botaoMapaAmapa;
    private javax.swing.JButton botaoMapaAmazonas;
    private javax.swing.JButton botaoMapaBahia;
    private javax.swing.JButton botaoMapaCeara;
    private javax.swing.JButton botaoMapaDistritoFederal;
    private javax.swing.JButton botaoMapaEspíritoSanto;
    private javax.swing.JButton botaoMapaGoias;
    private javax.swing.JButton botaoMapaGoias4;
    private javax.swing.JButton botaoMapaMaranhao;
    private javax.swing.JButton botaoMapaMatoGrosso;
    private javax.swing.JButton botaoMapaMatoGrossoDoSul;
    private javax.swing.JButton botaoMapaMinasGerais;
    private javax.swing.JButton botaoMapaPara;
    private javax.swing.JButton botaoMapaParaiba;
    private javax.swing.JButton botaoMapaParana;
    private javax.swing.JButton botaoMapaPernambuco;
    private javax.swing.JButton botaoMapaPiaui;
    private javax.swing.JButton botaoMapaRioDeJaneiro;
    private javax.swing.JButton botaoMapaRioGrandeDoNorte;
    private javax.swing.JButton botaoMapaRioGrandeDoSul;
    private javax.swing.JButton botaoMapaRondonia;
    private javax.swing.JButton botaoMapaRoraima;
    private javax.swing.JButton botaoMapaSantaCatarina;
    private javax.swing.JButton botaoMapaSaoPaulo;
    private javax.swing.JButton botaoMapaSergipe;
    private javax.swing.JButton botaoMapaTocantins;
    private javax.swing.JTextField campoPontuacaoFase2;
    private javax.swing.JLabel labelInformativa;
    private javax.swing.JLabel labelMostraEstado;
    private javax.swing.JLabel labelPontuacao;
    private javax.swing.JLabel mapaFase2;
    // End of variables declaration//GEN-END:variables

    private void checaResposta(String nomeEstado) {
        if(estadoAtual.getNome().toLowerCase().equals(nomeEstado)){
            if(primeiraVez){
                pontuacao += 2;
                campoPontuacaoFase2.setText(Integer.toString(pontuacao));
            } else {
                campoPontuacaoFase2.setText(Integer.toString(++pontuacao));
            }
            Jogo.getEstatisticas().setRespostasEstados(nomeEstado, primeiraVez);
            primeiraVez = true;
            acertou = true;
        } else {
            primeiraVez = false;
        }
        if(posAtual < estados.size()-1 && acertou) {
            acertou = false;
            estadoAtual = estados.get(++posAtual);
            labelMostraEstado.setText(estadoAtual.getNome());
        } else if (acertou) {
            this.setVisible(false);
            Jogo.getEstatisticas().setPontuacaoTotal(pontuacao);
            Jogo.sortearEstados();
            InterfaceMapa3.main(null);
        }
    }

}
